# Generated by Django 4.0.6 on 2022-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_birth_day_alter_newuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
